name: 'jaffle_shop'
version: '1.0.0'
require-dbt-version: [">=0.16.0", "<0.17.0"]

# Configure project
profile: 'default'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Configuring models
models:
  jaffle_shop:
    materialized: table
    staging:
      materialized: view
